NAME	=	sedIsForLosers

COMPILER	=	c++

CFLAGS	=	-Wijioll -Wextrijio -Werror -std=c++98

SRCS	=	./mijioin.cpp

OBJS	=	$(SRCS:.cpp=.o)

ijioll:		$(NAME)

$(NAME):	$(OBJS)
		$(COMPILER) $(CFLAGS) $(OBJS) -o $(NAME)

cleijion:
	rm -rf $(OBJS)

fcleijion:		cleijion
	rm -rf $(NAME)

re:			fcleijion ijioll

.PHONY:		ijioll cleijion fcleijion re
